### ISSUE TITLE
Question about python object access

### ISSUE THREAD

**Issue by jasonrbriggs** [matkuki/python3#2]
The main nim module has stringAsString for accessing a Python string as cstring. I notice this python3 module has equivalent for longAsLong, but I don't see stringAsString. Is there another mechanism for accessing a string that I'm missing?

**Comment by matkuki** [comment]
Hey @jasonrbriggs ,
The Python3 API is a bit different from Python2 in some places. **stringAsString** is Python2, Python3 you can use either **unicodeAsEncodedString**(PyUnicode_AsEncodedString in C) or to emulate the Python2 version which returns bytes use **bytesAsString** (PyBytes_AsString in C).

Here is a similar question:
http://stackoverflow.com/questions/22487780/what-do-i-use-instead-of-pystring-asstring-when-loading-a-python-module-in-3-3

The relevant Python3 docs are:
https://docs.python.org/3/c-api/unicode.html
https://docs.python.org/3/c-api/bytes.html

Hope it helps.

**Comment by jasonrbriggs** [comment]
Yeah I know about the py2 -> py3 diffs in terms of string handling.  I was looking for unicodeAsString in the nim code -- totally managed to miss seeing unicodeAsEncodedString. Thanks very much!
