### ISSUE TITLE
Question: can it be used for writing Python extension modules ?

### ISSUE THREAD

**Issue by vlad0337187** [matkuki/python3#3]
Hello.

Can this wrapper be used for writing python extensions (which will be compiled to .so files, which are imported by Python) ?

(just like Cython does: it compiles to files, which can be imported as general Python modules)

Thank you.

Best regards,
Vladislav.

**Comment by matkuki** [comment]
Hey Vladislav,

Of course. If you need a working example check the **nim** directory of my ExCo editor:
https://github.com/matkuki/ExCo/tree/master/nim

The quick rundown of the process is:
- create the Nim code that you will use in Python3 (that is the **nim_styling.nim** file in the above link)
- create a Nim wrapper module that will expose the Nim code you need to Python3 (that is the **nim_lexers.nim** file in the above link)
- compile the Nim wrapper module to a **.h** and **.c** file using the Nim compiler flag **cc** (the result of this for the above link example will be **nim_lexers.c** inside the **nimcache** directory)
- compile the  resulting **.c** file using Python3's distutils (see the **setup.py** file in the above link for an example, it is made for my installation of Nim on Windows, so you will have to change the paths to your system configuration)

If you check the **nim_styling.nim** and **nim_lexers.nim** files a bit closer you will see that I tried to make the wrapper be usable as similar as possible to the C API (same or similar function/type/... names).

You can try to build the code in the above link by running **python3 build.py**. It works on Windows, to make it work on Linux, change line 19 in **setup.py** to point to your system's Nim installations **lib** directory. I do not have the option of testing it on MacOS, but I can help you troubleshoot, if you need.

If you need any more information, let me know.
Matic

**Comment by matkuki** [comment]
If you are looking for an automated way of integrating Nim with Python (don't know if Python3), check out:
- [**nim-pymod**](https://github.com/jboy/nim-pymod) (unmaintained)
- [**nimpy**](https://github.com/yglukhov/nimpy)

**Comment by vlad0337187** [comment]
@matkuki , thank you very much, I understood.
