### ISSUE TITLE
Maintenance plans

### ISSUE THREAD

**Issue by HugoP707** [matkuki/python3#4]
I see this hasnt been updated in a while, are there any plans on updating it?

**Comment by matkuki** [comment]
Hey @Albus70007 ,
Have you looked at nimpy (https://github.com/yglukhov/nimpy)?
It has seamless integration between Python3 and Nim.
Or do you need something that cannot be done in nimpy?

**Comment by HugoP707** [comment]
yes, i think i cant do what i want in nimpy yet

**Comment by matkuki** [comment]
Currently there are no plans to update it, but if you can tell me which part of the wrapper you need to be updated, I can have a quick look at it during the weekend.

PR are always welcome, though.
