### ISSUE TITLE
python3.nim(32, 27) Error: 'export' is  only allowed at top level

### ISSUE THREAD

**Issue by HugoP707** [matkuki/python3#5]
I am getting this weird error when i try to compile my code (transpiled from the python wiki for interoping with C/C++)
```nim
import python3


proc spam_system*(self: PyObjectPtr, args: PyObjectPtr): static PyObjectPtr {.cdecl.} =
  var
    command: ptr char
    sts: int

  if PyArg_ParseTuple(args, "s", &command) == 0:
    return nil
  
  sts = system(command)
  return PyLong_FromLong(sts)
```

i have no clue why it does that.

**Comment by matkuki** [comment]
Hey @Albus70007 ,
Took a look at the code and the `dynamic` part of the library should be working now.
Note that the `dynamic` part of the wrapper follows the Nim naming convention, so in the above example `PyLong_FromLong` is renamed to `longFromLong`.
